project:
  type: website

website:
  title: "Home"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Made with ❤️ and Quarto"
  navbar:
    right:
      - text: Home
        href: index.qmd
      
format:
  html:
    # backgroundcolor: "#b3e0dc"
    # fontcolor: "darkgreen"
    # linkcolor: "black"
    # mainfont: "sarif"
    # max-width: ... # width of the main text area of the pages
    # fontsize: 20px # base font size for website
    # linestretch: ... # distance between lines ofd text
    theme: [cosmo, styles.scss]

