project:
  type: website
  resources: 
    - "CNAME"

website:
  title: "Home"
  description: "Brewing up another R spell"
  site-url: https://ellisfranklin.com
  repo-url: https://github.com/ellfran-7/ellis_website
  repo-actions: [edit, source, issue]
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  navbar:
    title: Ellis FRANKLIN
    right:
      - text: Papers
        href: papers/index.qmd
        icon: journal-richtext
      - text: "{{< iconify bi envelope size=1.1em title='E-mail' >}}"
        href: "mailto:ellis.franklin@univ-lorraine.fr"
      - text: "{{< iconify bi github size=1.1em title='GitHub' >}}"
        href: https://github.com/ellfran-7
      - text: "{{< iconify bi linkedin size=1.1em title='LinkedIn' >}}" 
        href: https://www.linkedin.com/in/ellis-franklin-6188831ba/
      - text: "{{< iconify fa6-brands bluesky size=1.1em title='Bluesky' >}}"
        href: https://bsky.app/profile/elfrank7.bsky.social

  back-to-top-navigation: true
  page-footer:
    border: true
    left: "&#169; 2025 Ellis FRANKLIN.<br><small>Content licensed under [**CC BY-NC-SA 4.0**](https://creativecommons.org/licenses/by-nc-sa/4.0/).<br>
    Code licensed under [**MIT License**](LICENSE)
.</small>"
    center:
      # - text: Code of conduct
      #   href: coc.qmd
      # - text: Accessibility
      #   href: accessibility.qmd
      - text: License
        href: license.qmd
    right: "Made with ❤️ and Quarto"
      
  
format:
  html:
    # fontsize: 20px
    theme: styles.scss
    toc: true
    toc-depth: 4
    smooth-scroll: true
    link-external-newwindow: true
    code-link: true
    highlight-style: pygments

