project:
  type: website
  resources: 
    - "CNAME"

website:
  title: "Home"
  description: "Brewing up another R spell"
  site-url: https://ellisfranklin.com
  repo-url: https://github.com/ellfran-7/ellis_website
  # repo-actions: 
  #   - source
  #   - issue
  # twitter-card: 
  #   creator: "@elffran7"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  # page-navigation: true
  navbar:
    title: Ellis FRANKLIN 
    # logo:
    # logo-alt:
    # left: 
    #   - ...
    # right:
    #   - text: Talks
    #     href: talks.qmd
    #     icon: megaphone
    #   - text: Blog
    #     href: blog/index.qmd
    tools:
      - icon: github
        aria-label: GitHub
        href: https://github.com/ellfran-7
      - icon: linkedin
        aria-label: LinkedIn
        href: https://www.linkedin.com/in/ellis-franklin-6188831ba/
      - icon: mastodon
        aria-label: Mastodon
        href: https://mastodon.social/@elfrank
  page-footer:
    border: true
    left: "&#169; 2025 Ellis FRANKLIN"
    # center:
    #   - text: Code of conduct
    #     href: coc.qmd
    #   - text: Accessibility
    #     href: accessibility.qmd
    #   - text: License
    #     href: license.qmd
    right: "Made with ❤️ and Quarto"
      
  
format:
  html:
    fontsize: 15px
    theme: [cosmo, styles.scss]
    toc: true
    toc-depth: 4
    smooth-scroll: true
    link-external-newwindow: true
    code-link: true
    highlight-style: pygments

